---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, FAS, ASA, all-flash, ONTAP 
summary: 'La gamme de systèmes de stockage ONTAP de NetApp est conçue pour les applications d"entreprise qui nécessitent un stockage facile à gérer, rapide et sécurisé, avec une fiabilité à toute épreuve et un accès continu aux données.' 
---
= En savoir plus sur les systèmes matériels ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


Les systèmes matériels ONTAP de NetApp sont conçus pour les applications d'entreprise qui nécessitent un stockage facile à gérer, rapide et sécurisé, une fiabilité de grande qualité et un accès continu aux données.

Les systèmes matériels ONTAP de NetApp sont disponibles en configurations 100 % Flash (AFF), Flash hybride et HDD uniquement (FAS). Vous pouvez ainsi choisir la combinaison de supports de stockage qui répond le mieux à vos besoins en termes de performances, de capacité et de coût.

Vous pouvez mettre en cluster plusieurs combinaisons de modèles pour exécuter des charges de travail mixtes sur le même système de stockage et créer votre environnement en ajoutant un stockage nouvelle génération doté des dernières technologies.



== Systèmes FAS 100 % Flash (AFF)

Les systèmes AFF basés sur NVMe constituent une architecture scale-out robuste conçue pour les environnements virtualisés. Ils peuvent être déployés en tant que système indépendant ou Tier haute performance dans une configuration NetApp ONTAP.

Les configurations FAS 100 % Flash sont idéales pour les applications stratégiques : elles prennent en charge de nombreuses charges de travail, notamment les infrastructures de postes de travail virtuels (VDI) et les bases de données qui exigent de hautes performances, une latence faible et une grande fiabilité.

https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["Consultez la fiche technique AFF A-Series"^] et https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["Lire la fiche technique AFF C-Series"^].



== Tous les systèmes de baies SAN (ASA)

La baie SAN 100 % Flash (ASA) NetApp assure une expérience SAN simplifiée et dédiée en fournissant une disponibilité continue des données dans le cadre de bases de données d'entreprise stratégiques et d'autres workloads SAN via le protocole FCP ou iSCSI.

https://www.netapp.com/pdf.html?item=/media/19466-SB-4081.pdf["Lire la fiche technique ASA"^]



== Systèmes FAS Flash hybrides

Les systèmes FAS Flash hybrides sont une plateforme matérielle créée pour les environnements SAN et NAS partagés et consolidés qui requièrent une gestion avancée des données et une connexion simple au cloud.

Avec son matériel hautement disponible, les systèmes FAS Flash hybrides répondent de façon économique aux exigences des charges de travail en combinant la combinaison idéale de disques rotatifs traditionnels et Flash, Il constitue la solution idéale pour la sauvegarde et la conservation, la consolidation des applications métier générales et le contenu distribué.

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Lire la fiche technique FAS"^]



== MetroCluster

Les systèmes de stockage matériels ONTAP configurés avec la fonctionnalité MetroCluster d'ONTAP offrent une solution qui associe une mise en cluster basée sur les baies à la réplication synchrone pour fournir une disponibilité sans interruption et aucune perte de données. La configuration MetroCluster duplique immédiatement toutes les données stratégiques, transaction par transaction, ce qui vous permet d'accéder de façon ininterrompue aux applications et aux données.

Contrairement aux solutions standard de réplication des données, MetroCluster fonctionne en toute transparence avec l'environnement hôte sans qu'il soit nécessaire de créer ou de gérer des scripts de basculement complexes.

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["En savoir plus sur MetroCluster"^]



== Logiciel ONTAP

Le logiciel de gestion des données ONTAP est le logiciel de stockage en cluster qui exécute les systèmes matériels ONTAP. Avec un espace de noms global prenant en charge jusqu'à 24 nœuds matériels de tous types, le logiciel ONTAP prend en charge le stockage unifié (bloc et fichier). Vous pouvez ainsi gérer une consolidation importante des workloads à l'aide de l'interface graphique de ONTAP System Manager.

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["Lire la fiche technique ONTAP"^].



== Pour en savoir plus

* https://docs.netapp.com/us-en/ontap-systems/index.html["Documents AFF et FAS"^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentation MetroCluster"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentation ONTAP"^]

