---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, FAS, all-flash, ONTAP 
summary: 'La gamme de systèmes de stockage NetApp ONTAP est conçue pour les applications d"entreprise qui nécessitent un stockage facile à gérer, rapide et sécurisé avec une fiabilité exceptionnelle et un accès continu aux données.' 
---
= Découvrez la gamme de systèmes de stockage AFF et FAS
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


La gamme de systèmes de stockage NetApp AFF et FAS est conçue pour les applications d'entreprise qui nécessitent un stockage facile à gérer, rapide et sécurisé avec une fiabilité exceptionnelle et un accès continu aux données.

Les systèmes AFF et FAS sont disponibles dans des configurations 100 % Flash (AFF) et Flash hybrides et FAS (HDD uniquement). Vous avez ainsi la possibilité de choisir la combinaison de supports de stockage qui répond le mieux à vos besoins en termes de performances, de capacité et de coûts.

Vous pouvez mettre en cluster plusieurs combinaisons de modèles AFF et FAS pour exécuter des charges de travail mixtes sur le même système de stockage et créer votre environnement en ajoutant de nouvelles générations de stockage aux technologies les plus récentes.



== Systèmes FAS 100 % Flash (AFF)

Les systèmes AFF basés sur NVMe constituent une architecture scale-out robuste conçue pour les environnements virtualisés. Ils peuvent être déployés en tant que système indépendant ou Tier haute performance dans une configuration NetApp ONTAP.

Les configurations FAS 100 % Flash sont idéales pour les applications stratégiques : elles prennent en charge de nombreuses charges de travail, notamment les infrastructures de postes de travail virtuels (VDI) et les bases de données qui exigent de hautes performances, une latence faible et une grande fiabilité.

https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["Consultez la fiche technique AFF A-Series"^] et https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["Lire la fiche technique AFF C-Series"^].



== Systèmes FAS Flash hybrides

Les systèmes FAS Flash hybrides sont une plateforme matérielle créée pour les environnements SAN et NAS partagés et consolidés qui requièrent une gestion avancée des données et une connexion simple au cloud.

Avec son matériel hautement disponible, les systèmes FAS Flash hybrides répondent de façon économique aux exigences des charges de travail en combinant la combinaison idéale de disques rotatifs traditionnels et Flash, Il constitue la solution idéale pour la sauvegarde et la conservation, la consolidation des applications métier générales et le contenu distribué.

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Lire la fiche technique FAS"^]



== MetroCluster

Les systèmes de stockage AFF et FAS configurés avec la fonctionnalité MetroCluster d'ONTAP offrent une solution qui combine une mise en cluster basée sur les baies à la réplication synchrone pour assurer une disponibilité continue et éliminer toute perte de données. La configuration MetroCluster duplique immédiatement toutes les données stratégiques, transaction par transaction, ce qui vous permet d'accéder de façon ininterrompue aux applications et aux données.

Contrairement aux solutions standard de réplication des données, MetroCluster fonctionne en toute transparence avec l'environnement hôte sans qu'il soit nécessaire de créer ou de gérer des scripts de basculement complexes.

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["En savoir plus sur MetroCluster"^]



== Logiciel ONTAP

Le logiciel de gestion des données ONTAP est le logiciel de stockage en cluster sur lequel s'appuient les systèmes AFF et FAS. Grâce à un espace de noms global prenant en charge jusqu'à 24 nœuds AFF et FAS de tous types, le logiciel ONTAP prend en charge le stockage unifié (bloc et fichier), ce qui permet une consolidation significative des charges de travail que vous pouvez gérer à l'aide de l'interface graphique de ONTAP System Manager.

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["Lire la fiche technique ONTAP"^].



== Pour en savoir plus

* https://docs.netapp.com/us-en/ontap-systems/index.html["Documents AFF et FAS"^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentation MetroCluster"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentation ONTAP"^]

