---
settings:
  name: AFF and FAS Family
  search: ontap-systems,ontap-systems-upgrade,ontap-systems-switches,ontap-metrocluster
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation AFF et FAS
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: Tout
    tags: tag_storage_management,tag_storage_upgrade,tag_storage_hardware,tag_get_started
    class: active
  - title: Commencez
    tags: tag_get_started
  - title: Matériel du système
    tags: tag_storage_hardware
  - title: Mise à niveau du système
    tags: tag_storage_upgrade
  tiles:
  - title: Découvrez AFF et FAS
    icon: "./media/family.png"
    url: intro-family.html
    summary: Découvrez la gamme de systèmes de stockage AFF et FAS.
    tags: all, tag_get_started
  - title: Installation et maintenance de AFF et FAS
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/ontap-systems/index.html
    summary: Installez et gérez vos baies AFF, FAS ou SAN.
    tags: all, tag_storage_hardware
  - title: Mise à niveau de AFF et FAS
    icon: "./media/upgrade.png"
    url: https://docs.netapp.com/us-en/ontap-systems-upgrade/index.html
    summary: Mettez à niveau vos systèmes de stockage AFF et FAS.
    tags: all, tag_storage_upgrade
  - title: Commutateurs de cluster et de stockage
    icon: "./media/switch.png"
    url: https://docs.netapp.com/us-en/ontap-systems-switches/index.html
    summary: Installez, mettez à niveau et maintenez vos commutateurs de cluster et
      de stockage.
    tags: all, tag_storage_hardware, tag_storage_upgrade
  - title: ONTAP MetroCluster
    icon: "./media/metrocluster.png"
    url: https://docs.netapp.com/us-en/ontap-metrocluster/index.html
    summary: Installez, mettez à niveau ou développez vos configurations MetroCluster
      et effectuez une reprise après incident.
    tags: all, tag_storage_upgrade
